### ISSUE TITLE
Anjum 

### ISSUE THREAD

**Issue by Nikitapatel24** [DMU-CTEC2902/LC-Concept#1]
Anjum change your name in wiki because Gary doesn't know how to spell it. 

ASAP 
thank you 
Nikita

**Comment by anjum1213** [comment]
Hiiiiiiiiiiii

My name is ANJUM SACRANIE!!! NOT SACRAMENT haha

**Comment by Nikitapatel24** [comment]
Thank you for making the propose correction 

best regards 
np
