### ISSUE TITLE
Site style

### ISSUE THREAD

**Issue by vorschdrach** [DMU-CTEC2902/LC-Concept#14]
Gary is to work on Film views style

Anjum is to work on Actors/Gossip views style

separate stysheets to be developed by each developer and included in the shared layout view

Gary

**Comment by vorschdrach** [comment]
Gary - i will start this on thursday 28th

**Comment by anjum1213** [comment]
hi i have started a little but going to get used to it and try different variances for colour combinations etc..

**Comment by vorschdrach** [comment]
Done - Gary Nicolson
