### ISSUE TITLE
Colour

### ISSUE THREAD

**Issue by Nikitapatel24** [DMU-CTEC2902/LC-Concept#19]
Hello team 

could you make sure to use relevant colour in to the website such as the purple co lour is been used in most of the pages so could you keep the same colour or for actor page make it something similar Instead of having peach colour this doesn't look professional. 

Thank you

**Comment by Nikitapatel24** [comment]
I haven't receive any update from the colour side. 
Could you update it ASAP

Thank you 
Team

**Comment by anjum1213** [comment]
hello how u doing? good afternoon to you too.. could you please let me sort the structure then worry about the colour madam? nice seeing you next to me

**Comment by anjum1213** [comment]
yes okay will be done after structure and buttons added css is in process

**Comment by anjum1213** [comment]
hi colour has been updated since last week so closing issue 
thanks
