### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by Nikitapatel24** [DMU-CTEC2902/LC-Concept#4]
Hello Garry, Anjum 

I would like to see some work from you both such as how much you guys done it and what are you working on if you have any issued let me know over here.  Anjum I haven't receive anything from you yet could you please upload some work on here please. 

Thank you 
Nikita

**Comment by anjum1213** [comment]
hi,
as i said i am working on the labs and getting used to github and its concept..i spoke to garry before and he said to go through MVC so i am currently doing that
Anjum
