### ISSUE TITLE
Beginning the Filmsite

### ISSUE THREAD

**Issue by vorschdrach** [DMU-CTEC2902/LC-Concept#7]
Having read the PDF getting started with Entity Framework 6 code first using MVC 5, will use this a guide to building the site.

Committed a new blank initial solution ConceptFilms

Sprint Goal 

Build all Model classes based of Nikitas ERD
Populate with seed data
Scaffold for at least two controllers

1 ViewFilmDetailsAndReviews
2 ViewActorDetailsAndReviews

Full CRUD functionality irrespective of user permission - this will be addressed later

Have included Unit Tests
Have included User Authorization - not sure if i will use it as it has a complicated structure

Goal Date - Monday 25th april 2016 - tommorow

Gary Nicolson

**Comment by vorschdrach** [comment]
Done took 4 hours, taking tommorow off

well half done, have left actors for Anjum

Gary Nicolson

**Comment by Nikitapatel24** [comment]
Thank you Gary and looking forward from Anjum
